### ISSUE TITLE
bug in clipping with a hole

### ISSUE THREAD

**Issue by Fil** [mfogel/polygon-clipping#102]
Hello,

I'm testing this library in https://observablehq.com/@fil/hello-polygon-clipping ; kudos for the fast and accurate implementation! It's really hard to find a library that works :) 

I think there is an issue, if you bring the hole (ie the inverted Caspian Sea) onto South America (r0 ~= 239°), the hole is not clipped.

Here's what it gives with clip and then with xor (and a slightly different r0 so we can see better):

<img width="174" alt="clip" src="https://user-images.githubusercontent.com/7001/90275475-aa16be80-de62-11ea-84ad-1e5a986c1272.png">
<img width="153" alt="xor" src="https://user-images.githubusercontent.com/7001/90275482-ab47eb80-de62-11ea-81ec-7bfaacae061d.png">

**Comment by mfogel** [comment]
Thanks for the bug report @Fil 

The process to debug & hopefully fix this kind of issue I would employee is

- transform the inputs that are causing the problem into some files that can be dropped in as a new end-to-end test. They'd make a new directory here: https://github.com/mfogel/polygon-clipping/tree/master/test/end-to-end
- then manually simplify those coordinates down to the absolute shortest, simplest coordinates that still cause the bug to happen.
- then trace exactly how those coordinates are flowing through the algorithm, and figure out where things are going wrong and hopefully figure out a fix that doesn't break the other tests.

The first two steps are pretty generic, any chance you could set up a PR with those two already done?

Most of the bugs in this library end up being a product of floating-point round errors... which I'm not sure there is an easy fix to.

**Comment by Fil** [comment]
Sorry for the report: the bug was in my polygons (the hole was present as an independent polygon).
