### ISSUE TITLE
Difference Question

### ISSUE THREAD

**Issue by blu-towers** [mfogel/polygon-clipping#106]
In regards to the following:

- rings will not contain superfluous points (intermediate points along a straight line).

Is there a way to keep the extra points along a straight line for the outputted polygon as it is needed for my project.

**Comment by mfogel** [comment]
Good question @blu-towers 

There's no option to do that. But where that is done is here: https://github.com/mfogel/polygon-clipping/blob/268219cc/src/geom-out.js#L100. I think the only change that's needed is to comment out that one line

**Comment by blu-towers** [comment]
this worked many thanks for the help

**Comment by mudin** [comment]
@mfogel Would it be possible to add a config to control such cases?
I also need to ignore this line without changing the library code.
Thanks
