### ISSUE TITLE
Error: SweepEvent comparison failed at [0,600]... equal but not identical?

### ISSUE THREAD

**Issue by rgk** [mfogel/polygon-clipping#12]
Hi, when clipping multiple times I get this error. It seems to be triggered when I clip in a very similar or exactly the same spot, but this is mostly speculation.

Error: SweepEvent comparison failed at [0,600]... equal but not identical?
 at Heap.compareBefore [as _isBefore] (./node_modules/polygon-clipping/src/sweep-event.js:28:11)
 at Heap_remove (./node_modules/qheap/lib/qheap.js:91:18)
 at doIt (./node_modules/polygon-clipping/src/index.js:38:47)
 at Object.difference (./node_modules/polygon-clipping/main.js:17:10)

Version: 0.6

Just want to state, great work, my current use case is to create destructable ground with matterjs using this library to make the holes.

**Comment by mfogel** [comment]
@rgk thanks for the bug report. Can you upload the shapes you're using as input? If they're big shapes, you could make a [gist](https://gist.github.com/) or [attach files to this issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by rgk** [comment]
@mfogel I am closing this. I have been doing a lot of debugging and figured out I was handling multipolygons wrong. Once a polygon is broken into two or more, the error was being triggered and I fixed it by inputting a proper a multipolygon array.

Once again great library, I have included it in on the credits page: https://aerialdrop.com/credits
