### ISSUE TITLE
export 'default' (imported as 'polygonClipping') was not found in 'polygon-clipping' (module has no exports)

### ISSUE THREAD

**Issue by leshalv** [mfogel/polygon-clipping#159]
This error occurs with the new version

**Comment by mfogel** [comment]
Thanks, looking into it.

**Comment by mfogel** [comment]
Ok, I've released `v0.15.5` which just reverts to v0.15.3 which should fix this problem.

I'm going to leave this issue open so other folks see it if they run into it, but this should be fixed as of `v0.15.5`. Let me know if you see otherwise please.

**Comment by leshalv** [comment]
v0.15.5 effective
