### ISSUE TITLE
Rollup failed to resolve import "robust-predicates" from polygon-clipping

### ISSUE THREAD

**Issue by YangChen0930** [mfogel/polygon-clipping#162]
This error occurs with the new version

![image](https://github.com/mfogel/polygon-clipping/assets/27183388/9bd1d14a-9e4d-48cc-9514-911915da55f9)

**Comment by shuanglei7** [comment]
I also encountered the same problem

**Comment by shuanglei7** [comment]
I reverted to v0.15.5, fixed this problem tentatively.

**Comment by mfogel** [comment]
Ok, I've released `v0.15.7` to npm which should fix this problem. Please give it a try when you get a chance.

(tests are failing on `main` just do to some codecov/github rate limiting, unrelated to this issue)

**Comment by havocbane** [comment]
Thanks, this change fixed the issue for us.
