### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'POLYGON_CLIPPING_MAX_QUEUE_SIZE')

### ISSUE THREAD

**Issue by artemrsx** [mfogel/polygon-clipping#165]
**Reproduction**
https://stackblitz.com/edit/nuxt-starter-e8wsmf?file=package.json

**Describe the bug**
When trying to include polygon-clipping, get an error `Cannot read properties of undefined (reading 'POLYGON_CLIPPING_MAX_QUEUE_SIZE')` because we have `process` but don't have `env` in nuxt 3 project.

Can u check for `process` and `process.env` [here](https://github.com/mfogel/polygon-clipping/blob/e2c6aed942a37c3fe5476dac1e3f1b91632e396e/src/operation.js#L10) ?

**Comment by mfogel** [comment]
Thanks for the raising the issue @artemrsx . Pull requests happily entertained.

**Comment by mfogel** [comment]
Fixed by #167
