### ISSUE TITLE
splaytree event is null?

### ISSUE THREAD

**Issue by rgk** [mfogel/polygon-clipping#22]
Version 0.7

This error seems to happen randomly when doing quick clippings with difference.

TypeError: Cannot read property 'left' of null
    at Tree.prev (webpack://polygon-clipping/./node_modules/splaytree/index.js?:537:11)
    at SweepLine.process (webpack://polygon-clipping/./src/sweep-line.js?:52:32)
    at doIt (webpack://polygon-clipping/./src/index.js?:73:31)
    at Object.difference (webpack://polygon-clipping/./main.js?:47:28)

**Comment by mfogel** [comment]
Hi @rgk , thanks for the bug report

What version of polygon-clipping are you using? I just released a v0.7 yesterday, which included an update of splaytree. If you're not on v0.7 already, probably worthwhile upgrading and see if that fixes the problem.

If that doesn't fix the problem - could you post some of the input polygons you're using here? To debug the issue I need to reproduce it first. Thank you!

**Comment by rgk** [comment]
@mfogel sorry about the delay, I didn't want to waste your time so I made sure this wasn't an error with how I was using it.

`var mapPolygon = [[[[0,700],[1346.6372247387783,700],[1346.6372247387783,701.917260520819],[1348.0802247387783,707.769260520819],[1350.8802247387782,713.106260520819],[1354.8772247387783,717.617260520819],[1359.8372247387783,721.040260520819],[1365.4722247387783,723.178260520819],[1367.8294157208477,723.4642910494806],[1367.5094929038385,723.8253548041789],[1364.7094929038385,729.1623548041789],[1363.2664929038385,735.0143548041789],[1363.2664929038385,736.9396515443838],[1362.9292184203384,738.3074479944479],[1362.9292184203384,744.333447994448],[1364.3722184203384,750.1854479944479],[1364.922709328376,751.2347229859467],[1362.454667543475,755.9389869166671],[1361.011667543475,761.7909869166671],[1361.011667543475,767.8169869166671],[1361.129655167017,768.2954786512262],[1361.129655167017,770.0522636043432],[1362.572655167017,775.9042636043432],[1365.372655167017,781.2412636043432],[1369.369655167017,785.7522636043432],[1374.329655167017,789.1752636043432],[1379.964655167017,791.3132636043432],[1385.947655167017,792.0392636043432],[1391.930655167017,791.3132636043432],[1395.056522253388,790.1272646991681],[1395.056522253388,790.6311069941822],[1396.2609084334053,795.5154229508429],[1394.4946830083165,796.1855542656325],[1389.5346830083165,799.6085542656325],[1385.5376830083164,804.1195542656325],[1382.7376830083165,809.4565542656325],[1381.2946830083165,815.3085542656324],[1381.2946830083165,822.1282047763995],[1382.7376830083165,827.9802047763994],[1385.5376830083164,833.3172047763994],[1389.5346830083165,837.8282047763994],[1394.4946830083165,841.2512047763994],[1400.1296830083165,843.3892047763994],[1406.1126830083165,844.1152047763994],[1408.3607649019398,843.8424139599578],[1406.7315241640815,846.9478631806543],[1406.7102439117257,847.0341639684476],[1403.8431442151473,848.1219828062976],[1403.2696646478264,848.5177530802774],[1402.7655450169702,848.7090233146644],[1397.8055450169702,852.1320233146644],[1393.8085450169701,856.6430233146643],[1391.0085450169702,861.9800233146643],[1390.995212583186,862.0340922006686],[1390.0258590813924,863.8817492146235],[1388.5828590813924,869.7337492146235],[1388.5828590813924,875.7597492146235],[1389.5735419869914,879.7774043522295],[1387.6523887461033,881.9456110746829],[1384.8523887461033,887.2826110746829],[1383.4093887461033,893.1346110746829],[1383.4093887461033,899.160611074683],[1384.8523887461033,905.0126110746829],[1387.6523887461033,910.3496110746829],[1391.6493887461033,914.8606110746829],[1396.6093887461034,918.2836110746829],[1402.2443887461034,920.4216110746829],[1408.2273887461033,921.1476110746829],[1414.2103887461033,920.4216110746829],[1419.8453887461033,918.2836110746829],[1424.8053887461033,914.8606110746829],[1428.8023887461034,910.3496110746829],[1431.6023887461033,905.0126110746829],[1433.0453887461033,899.160611074683],[1433.0453887461033,893.1346110746829],[1432.0547058405043,889.1169559370768],[1433.9758590813924,886.9487492146235],[1434.186201445866,886.5478216434827],[1436.0361442151473,884.4599828062976],[1438.3961102055414,879.9617190596072],[1441.7245241640815,878.6988709596321],[1445.0763932280597,876.3856758374551],[1450.026781887207,879.8020428496045],[1455.661781887207,881.9400428496045],[1461.644781887207,882.6660428496045],[1467.627781887207,881.9400428496045],[1473.262781887207,879.8020428496045],[1478.222781887207,876.3790428496045],[1482.219781887207,871.8680428496045],[1485.019781887207,866.5310428496045],[1486.462781887207,860.6790428496046],[1486.462781887207,854.6530428496045],[1485.019781887207,848.8010428496045],[1482.219781887207,843.4640428496045],[1478.222781887207,838.9530428496046],[1475.3406178602559,836.9640010221343],[1475.9856043630527,834.3482969234744],[1475.9856043630527,828.3222969234744],[1474.5426043630528,822.4702969234744],[1471.7426043630528,817.1332969234744],[1467.7456043630527,812.6222969234744],[1462.7856043630527,809.1992969234744],[1457.1506043630527,807.0612969234744],[1451.4256593609832,806.3666102994559],[1450.1921517045414,801.36419394083],[1447.3921517045414,796.02719394083],[1444.239343588906,792.4689459023934],[1444.692522253388,790.6311069941822],[1444.692522253388,784.6051069941822],[1443.249522253388,778.7531069941822],[1440.449522253388,773.4161069941822],[1439.7677746876195,772.6466891134762],[1441.1906571347554,766.876274643179],[1441.1906571347554,760.850274643179],[1439.7476571347554,754.998274643179],[1436.9476571347554,749.661274643179],[1436.4938214118033,749.1490772585812],[1437.3658597240226,745.6125781573286],[1437.3658597240226,738.4161036443184],[1435.9228597240226,732.5641036443184],[1433.1228597240226,727.2271036443184],[1431.7828717895,725.7147980219434],[1435.6042625514162,721.4019899841638],[1438.4042625514162,716.0649899841638],[1439.8472625514162,710.2129899841639],[1439.8472625514162,710.1839531770769],[1440.569253195457,707.2559633995812],[1440.569253195457,706.8899622780598],[1440.7602930754492,706.1152114965524],[1440.7602930754492,700.0892114965524],[1440.7382950936437,700],[2600,700],[2600,1000],[0,1000]]]];
var holePolygon = [[[1486.462781887207,860.6790428496046],[1485.019781887207,866.5310428496045],[1482.219781887207,871.8680428496045],[1478.222781887207,876.3790428496045],[1473.262781887207,879.8020428496045],[1467.627781887207,881.9400428496045],[1461.644781887207,882.6660428496045],[1455.661781887207,881.9400428496045],[1450.026781887207,879.8020428496045],[1445.066781887207,876.3790428496045],[1441.069781887207,871.8680428496045],[1438.269781887207,866.5310428496045],[1436.826781887207,860.6790428496046],[1436.826781887207,854.6530428496045],[1438.269781887207,848.8010428496045],[1441.069781887207,843.4640428496045],[1445.066781887207,838.9530428496046],[1450.026781887207,835.5300428496046],[1455.661781887207,833.3920428496045],[1461.644781887207,832.6660428496045],[1467.627781887207,833.3920428496045],[1473.262781887207,835.5300428496046],[1478.222781887207,838.9530428496046],[1482.219781887207,843.4640428496045],[1485.019781887207,848.8010428496045],[1486.462781887207,854.6530428496045]]];

var clippedPolygon = polygonClipping.difference(mapPolygon, holePolygon);`

**Comment by mfogel** [comment]
Awesome, thanks - I've reproduced the error on my side.

It is likely that rounding the values will make the problem go away, so if your application doesn't need that high precision and you want to move forward right away, I would try that.

In any case thanks for the failing polygons, I will find time in the next week to take a deep dive into these and figure out what's going on. Cheers.

**Comment by rgk** [comment]
Here is another example with no floating points:

var mapPolygon = [[[[0,700],[882,700],[885,704],[889,709],[893,719],[897,723],[902,726],[904,727],[908,735],[912,739],[916,741],[916,744],[918,750],[921,755],[925,760],[930,763],[930,766],[930,770],[930,771],[927,776],[926,782],[926,788],[927,794],[930,799],[934,804],[939,807],[945,810],[957,810],[967,804],[971,799],[974,794],[976,788],[976,782],[974,778],[975,778],[978,772],[979,766],[979,760],[978,755],[975,749],[971,745],[966,741],[966,738],[965,732],[962,727],[958,722],[953,719],[953,717],[958,715],[963,711],[967,707],[970,701],[970,700],[2600,700],[2600,1000],[0,1000],[0,700]]]];
var holePolygon = [[[[960,807],[959,813],[956,818],[952,822],[947,826],[941,828],[935,829],[929,828],[924,826],[919,822],[915,818],[912,813],[910,807],[910,801],[912,795],[915,789],[919,785],[924,782],[929,779],[935,779],[941,779],[947,782],[952,785],[956,789],[959,795],[960,801]]],[[[960,807],[959,813],[956,818],[952,822],[947,826],[941,828],[935,829],[929,828],[924,826],[919,822],[915,818],[912,813],[910,807],[910,801],[912,795],[915,789],[919,785],[924,782],[929,779],[935,779],[941,779],[947,782],[952,785],[956,789],[959,795],[960,801]]],[[[960,807],[959,813],[956,818],[952,822],[947,826],[941,828],[935,829],[929,828],[924,826],[919,822],[915,818],[912,813],[910,807],[910,801],[912,795],[915,789],[919,785],[924,782],[929,779],[935,779],[941,779],[947,782],[952,785],[956,789],[959,795],[960,801]]]];

var clippedPolygon = polygonClipping.difference(mapPolygon, holePolygon);

**Comment by mfogel** [comment]
Here's a simplified geometry that still reproduces the error:

```js
> pc = require('./dist/polygon-clipping')
> subject = [[[900, 0], [950, 85], [1000, 0], [1000, 100], [900, 100], [900, 0]]]
> clipping = [[[945, 83], [959, 80], [950, 90], [945, 83]]]
> pc.difference(subject, clipping, clipping)
TypeError: Cannot read property 'left' of null
    at Tree.prev (webpack://polygon-clipping/./node_modules/splaytree/index.js?:537:11)
    at SweepLine.process (webpack://polygon-clipping/./src/sweep-line.js?:52:32)
    at doIt (webpack://polygon-clipping/./src/index.js?:73:31)
    at Object.difference (webpack://polygon-clipping/./main.js?:47:28)
```

**Comment by nwesterman** [comment]
I've run into this with Union as well using the polygons below.

```
const poly1 = [[[-96.70241693762678,43.70114184402157],[-96.70241693762678,43.70119666666667],[-96.70242360429344,43.70119666666667],[-96.70242360429346,43.70114184402157],[-96.70241693762678,43.70114184402157]]]
const poly2 = [[[-96.70241693762678,43.701196666666654],[-96.70241693762678,43.70125148931175],[-96.70242360429346,43.70125148931175],[-96.70242360429346,43.701196666666654],[-96.70241693762678,43.701196666666654]]]

const polyOut = polygonClipping.union(poly1, poly2)
```

```
webpack://polygon-clipping/./node_modules/splaytree/index.js?:537
    if (d.left !== null) {
          ^
TypeError: Cannot read property 'left' of null
    at Tree.prev (webpack://polygon-clipping/./node_modules/splaytree/index.js?:537:11)
    at SweepLine.process (webpack://polygon-clipping/./src/sweep-line.js?:52:32)
    at doIt (webpack://polygon-clipping/./src/index.js?:73:31)
    at Object.union (webpack://polygon-clipping/./main.js?:23:28)
```

**Comment by mfogel** [comment]
thanks for the additional example @nwesterman 

Update - I haven't gone completely AWOL on this.

These examples of error conditions, and a lot of the end-to-end test suite essentially deals with floating point errors. Calculate the intersection of two lines - and the resulting point appears to be on neither of them. Calculate the intersection of two lines - then reverse one and calculate the intersection again - and get slightly different results.

I've resisted doing any truncation of trailing digits and tried to just go with the max precision offered by the javascript interpreter - that is `Number.EPSILON`. But I may need to relax that.

**Comment by mfogel** [comment]
Progress update: what's now on the [feature/drop-coincident-segments-sooner](https://github.com/mfogel/polygon-clipping/tree/feature/drop-coincident-segments-sooner) branch fixes all the failing cases mentioned in this thread except one. That one, I have reduced to the following minimal failing test case:

```js
const polygonClipping = require('./dist/polygon-clipping.js')
const p1 = [ [  [270, 30], [275.340617860256, 33.9640010221343], [279, 30], [279, 39], [270, 30] ] ]
const p2 = [ [ [275, 34], [273.262781887207, 32.5300428496046], [278.222781887207, 35.9530428496046], [275, 34] ] ]

polygonClipping.difference(p1, p2)
TypeError: Cannot read property 'left' of null
    at Tree.prev (webpack://polygon-clipping/./node_modules/splaytree/index.js?:537:11)
    at SweepLine.process (webpack://polygon-clipping/./src/sweep-line.js?:51:32)
    at doIt (webpack://polygon-clipping/./src/index.js?:74:31)
    at Object.difference (webpack://polygon-clipping/./main.js?:47:28)
```

Hoping to get time to dig deeper into this failing case tomorrow.

**Comment by mfogel** [comment]
I've gone ahead and moved the remaining failing test case to a new issue, because it seems to be triggering a pretty distinct failure than the other cases on this thread. Thanks much for the bugs folks, and please report more as you run across them.
