### ISSUE TITLE
No default es6 export

### ISSUE THREAD

**Issue by goldfire** [mfogel/polygon-clipping#33]
Not a big deal, but when using this with webpack/babel, the following doesn't work:

    import polygonClipping from 'polygon-clipping';

You are forced to used the require syntax in order for the module to be found.

**Comment by mfogel** [comment]
Thanks for the bug report @goldfire, appreciate it

I'm going to fix this in the next version so the import syntax you have above works, but it looks like on the current version (0.7) you can do

```js
    import * as polygonClipping from 'polygon-clipping'
```
