### ISSUE TITLE
Fixing Self-Intersecting rings?

### ISSUE THREAD

**Issue by rgk** [mfogel/polygon-clipping#34]
Error: Self-intersecting, crossing input ring found at [1159.7391304347825, 863.0434782608695]

I am not sure if this is a bug or an issue with my input, I am assuming its an issue with my input. How would I fix this normally with js? Otherwise if it is a bug I can give more information.

**Comment by mfogel** [comment]
Hi @rgk, the latest that's on the master branch in this repo should handle self-crossing rings ok. I haven't yet done a new release to npm with that change in it yet, though I plan to this weekend or early next week.

You probably already saw this, but there's more details about this on #30
