### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jliebrand** [mfogel/polygon-clipping#38]
For certain input values, there appears to be an infinite loop causing a max stack size to be reached. 

I'll add a test case and a PR to show the issue (raising this issue first so that i can refer to it in code)

**Comment by jliebrand** [comment]
See PR
https://github.com/mfogel/polygon-clipping/pull/39

**Comment by jliebrand** [comment]
@mfogel - I assume you dont want the PR to land without a fix, or else your build is broken? Any update on a potential fix?

**Comment by mfogel** [comment]
@jliebrand - yeah I don't want to merge in just the failing test case individually, at least not to master. I haven't had time to look at this bug yet, will hopefully get time ASAP but I can't promise. :/

**Comment by jliebrand** [comment]
Ok great, I'll keep my eyes on this bug for now then :-)
