### ISSUE TITLE
Infinite loop in union

### ISSUE THREAD

**Issue by jliebrand** [mfogel/polygon-clipping#42]
I've come across cases where the queue behaves badly, such that the algorithm ends up in an eternal loop. Notice this screenshot:

![image](https://user-images.githubusercontent.com/23407884/47022116-b17cbc00-d154-11e8-9c8d-76a1e4f04c83.png)

Notice in the console, how the queue size is 7,154 elements, but even after calling pop(), it is still the same length... Causing the while loop to spin forever...

**Comment by jliebrand** [comment]
Here is a gist containing the coordinates that caused this eternal loop:

https://gist.github.com/jliebrand/7c0f80d8fa52bfae5a9e7066d162c434

**Comment by jliebrand** [comment]
I created a quick PR to break out of this error case... it doesn't solve the underlying bug, but at least it stops things from spinning forever...

**Comment by jliebrand** [comment]
PR https://github.com/mfogel/polygon-clipping/pull/43

**Comment by mfogel** [comment]
And, [the fix](https://github.com/mfogel/polygon-clipping/commit/9c82aba4276bea7762b71bcbcdb3c2a375cfa0cd) for #36 appears to have fixed this one as well.
