### ISSUE TITLE
Union failed and throws "SweepEvent comparison failed" error

### ISSUE THREAD

**Issue by jcarbou** [mfogel/polygon-clipping#53]
First, thank you for you lib !

I generated a polygon using bbox clip on OSM Land polygon (http://openstreetmapdata.com/data/land-polygons). I try to generate a polygonClipping.union using the MultiPolygon generated. Error throws 

Error: SweepEvent comparison failed at [-15.188987939241656, 11]... equal but not identical?

I simplified the polygons to reproduce the bug:

```
// The problem comes from this polygon
const p1 = [[[-15.17583125361432, 11], [-15.182247200000006, 10.996678799999998], [-15.186977083599459, 11], [-15.188987939241656, 11], [-15.210785900000019, 10.987789800000002], [-15.25473119999998, 10.999922499999997], [-15.25484460019419, 11], [-15.17583125361432, 11]]];

// p2 : any polygon intersecting p1 or not
const p2 = [[[-15.017809399999976, 10.944376500000018], [-15.012765219284972, 10.95029830701516], [-15.013805400000024, 10.942978100000005], [-15.017809399999976, 10.944376500000018]]];

polygonClipping.union(p1,p2);
```

The problem comes from this strange polygon (2 areas linked by a line !!!) 

![view](https://user-images.githubusercontent.com/12503702/50118099-f6a19500-024e-11e9-8b25-e02f86fbbbd8.png)

**Comment by rowanwins** [comment]
Resolved by this [commit](https://github.com/mfogel/polygon-clipping/commit/d55f17f52488c5011d94eb6281fc80945ff6c1a9)

**Comment by mfogel** [comment]
Thanks @jcarbou for bug report and @rowanwins for testing this with the latest on master.

Verified resolved, fix will be included in the next release to NPM.

To others who encounter this error behavior but with a different set of input coordinates - please open a new issue rather than re-open this one.
