### ISSUE TITLE
Regression between v7 & v8

### ISSUE THREAD

**Issue by rowanwins** [mfogel/polygon-clipping#54]
Hi @mfogel 

When updating this module in turf in line with #50 I've now got some tests which fail which previously passed.

I'm basically just trying to union a massive feature collection ([here it is](https://gist.github.com/rowanwins/c029f2059a5c21a8cef14c523d75643d)). 

Nothing fancy, just 
````
const args = fc.features.map(f => f.geometry.coordinates)
pc.union(...args))
````
Hunting back through the repo history I can see it worked with v7, however it breaks in v8 throwing a splaytree error. And in v9.2 it spins infinitely...

Will see if I can narrow down the test case at all 

Cheers

**Comment by rowanwins** [comment]
Okie dokie well I've managed to narrow down the test case to 5 polygons
https://gist.github.com/rowanwins/7da6ec92059833bc71d6b3899a308e7d

Hopefully slightly more manageable to debug :)

**Comment by mfogel** [comment]
Hi @rowanwins thanks for the bug report & simplifying down the polygons. I was able to simplify the situation some more to [this test case](https://github.com/mfogel/polygon-clipping/blob/72412127997fee25da41d70c29c7d32b57fb3f29/test/end-to-end/almost-colinear-segments-but-not-2/args.geojson), and then from there figure out the fix.

Let me know if the fix does or does not work for you.

I suspect this change probably fixed some of the other open bugs as well - I need to do a pass through those open tickets and run them against master.

**Comment by rowanwins** [comment]
That's done the job thanks @mfogel!
