### ISSUE TITLE
Update to splaytree 3.0.0 

### ISSUE THREAD

**Issue by rowanwins** [mfogel/polygon-clipping#72]
I just noticed some treeshaking issues in turf which I think are coming via `polygon-clipping` because of it's use of It splaytree v2.3.0. From what I can tell splaytree wasn't very friendly for treeshaking (I suspect lines like [this](https://github.com/w8r/splay-tree/blob/ec284bf3f3af050d101ed1ca8710868d57f70195/dist/splay.js#L674)).

Splaytree has recently be rewritten in typescript and it looks like v3.0.0 removes those sorts of issues.

So if we could run an upgrade on that dependency that would be helpful.

Thanks :)

**Comment by mfogel** [comment]
Tests were passing with Splaytree v3.0 so I'm going to assume it's all good. Thanks for the PR - merged.

If I had an extra 10 hours a week I would love to embark on a rewrite of this project in typescript, but... I feel like I'm struggling to find enough time for it as it is.

**Comment by rowanwins** [comment]
All good @mfogel - i sympathise :)

**Comment by rowanwins** [comment]
Is there any chance of getting this out as a minor release, eg `v0.14.1` @mfogel ?

**Comment by mfogel** [comment]
sure, why not :) published!

**Comment by huangjianke** [comment]
No matching version found for polygon-clipping@^0.14.1

@mfogel

**Comment by mfogel** [comment]
@huangjianke not sure what's going on in your env but [v0.14.1 is live on npm](https://www.npmjs.com/package/polygon-clipping/v/0.14.1). I just did a test `npm install polygon-clipping@^0.14.1` from my dev env and it worked for me. Cheers.
