### ISSUE TITLE
Using robust predicates and another intersection lib

### ISSUE THREAD

**Issue by rowanwins** [mfogel/polygon-clipping#89]
Hey @mfogel 

Been a while since I looked at this repo but I've recently been making another push on my new buffering/offsetting library and so I started re-looking at the performance and stability of this lib as I'm in need of a decent union operation :)

One notable thing that's happened in the js geometry world is that a library called [`robust-predicates`](https://github.com/mourner/robust-predicates) has been released. Of particular interest is to this lib might be the [orient2d](https://github.com/mourner/robust-predicates#orient2daxay-bxby-cxcy) method. There is a neat [interactive demo here](https://observablehq.com/@mourner/non-robust-arithmetic-as-art). I'm thinking this would possibly help with some of the bits in `src/vector.js`.

Another thing I've released recently is a [sweepline intersection](https://github.com/rowanwins/sweepline-intersections) library. I started off trying to write a bentley-ottmann algorithm for the task, which I did [eventually complete](https://github.com/rowanwins/bentley-ottmann-intersections). While working on it I had a thought that the algorithm could be greatly simplified by removing the tree structure of the segments. It turned out removing the tree structure didn't actually degrade performance, in fact it improved it, and so I wonder if the same learning might be applicable to the martinez algorithm...

Anyway just a few suggestions :)

**Comment by mfogel** [comment]
Thanks for the pointers. robust-predicates looks useful. I pulled that out into a separate task in hopes that it might attract the attention of somebody out there wants to try to contribute a PR. My free time is pretty limited these days :(
