### ISSUE TITLE
Is this usable in a browser?

### ISSUE THREAD

**Issue by Qrokqt** [mfogel/polygon-clipping#99]
I tried the umd in a browser and got and error, "Uncaught ReferenceError: process is not defined".

**Comment by mfogel** [comment]
@Qrokqt thanks for the heads up. This package certainly should be useable in the browser.

I just pushed a fix for this to the master branch. Are you able to try running the latest on master and see if it fixes it for you? If so I will issue a new release to npmjs ASAP.

**Comment by Qrokqt** [comment]
Yeah, it seems to work now. I don't get any errors.

**Comment by mfogel** [comment]
Ok I've pushed a new version `v0.15.1` to npm with a fix for this. Thanks again for the heads up
